apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydatabase-deployment
  namespace: default
  labels:
    app: mydatabase
spec:
  selector:
    matchLabels:
      app: mydatabase
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mydatabase
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: POSTGRES_USER
          valueFrom: 
            configMapKeyRef:
              name: mydatabase-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: mydatabase-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef:
              name: mydatabase-config
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: mydatabase-storage
      volumes:
      - name: mydatabase-storage
        persistentVolumeClaim:
          claimName: mydatabase-pvc
