stages:
  - checks

apichecker:
  stage: checks
  script: 
     - curl "https://jsonplaceholder.typicode.com/users"

daychecker:
  stage: checks
  script:
     - chmod u+x ./checkDate.sh
     - ./checkDate.sh
  only:
     - merge_requests

sizechecker:
  stage: checks
  script:
    - chmod u+x ./checkSize.sh
    - echo ${MAXIMUM_WEIGHT}
    - ./checkSize.sh ${MAXIMUM_WEIGHT}
