services:
  nginx:
    image: nginx:stable
    volumes:
    - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80

  prometheus:
      image: prom/prometheus:v2.45.2
      user: root
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/first_rules.yml:/etc/prometheus/first_rules.yml
        - ./prometheus/data:/prometheus
      container_name: prometheus
      restart: always
      networks:
        - localhost
      ports:
        - 9090:9090

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0 
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=http://localhost:8080/stub_status
    expose: 
      - 9113
    ports:
      - 9113:9113
    networks:
      - localhost
    depends_on:
      - prometheus

  prometheus-node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: prometheus-node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - localhost
    privileged: true
    depends_on:
      - prometheus
    expose:
      - 9100
    ports:
      - 9100

  alertmanager:
      image: prom/alertmanager:latest
      restart: unless-stopped
      expose:
        - 9093
      ports:
        - "9093:9093"
      volumes:
        - "./prometheus/alertmanager:/config"
        - alertmanager-data:/data
      command: --config.file=/config/alertmanager.yml --log.level=debug

volumes:

  alertmanager-data:

networks:
    localhost:
        name: localhost
