apiVersion: v1
kind: Service
metadata:
  name: rollingapp-service
  namespace: default
  labels:
    app: rollingapp
spec:
  selector:
    app: rollingapp
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port:  80
    targetPort: 80
