apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingapp-deployment
  namespace: default
  labels:
    app: rollingapp
spec:

  selector:
    matchLabels:
      app: rollingapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rollingapp
    spec:
      containers:
      - name: nginx-hello
        image:  nginxdemos/hello:latest
        ports:
        - containerPort:  80
