stages:
  - stage1

displayinfos:
  stage: stage1
  script:
     - echo "Commit author is ${CI_COMMIT_AUTHOR}"
     - echo "Commit id is ${CI_COMMIT_SHA}"
     - echo "List of edited files in this Commit $(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA)"

check-author:
  stage: stage1
  script:
     - chmod u+x ./checkAuthor.sh
     - ./checkAuthor.sh "${CI_COMMIT_AUTHOR}"
