apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-server-deployment
  namespace: webapp-prod # added namespace
  labels:
    app: httpd-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      labels:
        app: httpd-server
    spec:
      containers:
      - name: httpd-server
        image: httpd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
