apiVersion: v1
kind: Service
metadata:
  name: mws-service
  labels:
    app: mywebserver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebserver
  sessionAffinity: None
